name: Deploy MkDocs
on: push
jobs:
  deploy:
    runs-on: puzl-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-material
      - run: mkdocs gh-deploy --clean --force
